name: Deploy to Cloudflare Workers

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
          
      - name: Install dependencies
        run: npm install
        
      - name: Cache Wrangler
        uses: actions/cache@v4
        with:
          path: ~/.wrangler
          key: ${{ runner.os }}-wrangler-${{ hashFiles('wrangler.toml') }}
          restore-keys: |
            ${{ runner.os }}-wrangler-
        
      - name: Install Wrangler
        run: npm install -g wrangler@3.78.12
        
      - name: Deploy to Cloudflare Workers
        run: wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

